#!/usr/bin/env bash

if [ "$1" = "test" ]; then
    uv run --locked --no-sync --no-cache "test-one.py" "$2"
elif [ "$1" = "version" ]; then
    uv export -q --no-cache | grep ^mf2py== | cut -d ' ' -f 1 | cut -d '=' -f 3
elif [ "$1" = "compile" ]; then
    true
elif [ "$1" = "setup" ]; then
    uv sync --locked -q --no-cache
elif [ "$1" = "update" ]; then
    uv lock --upgrade -q --no-cache
    uv sync -q --no-cache
fi