#!/usr/bin/env bash

if [ "$1" = "test" ]; then
    ruby "test-one.rb" "$2"
elif [ "$1" = "version" ]; then
    bundle info microformats --version
elif [ "$1" = "compile" ]; then
    true
elif [ "$1" = "setup" ]; then
    bundle install --quiet
elif [ "$1" = "update" ]; then
    bundle update --all --quiet
fi