#!/usr/bin/env bash

if [ "$1" = "test" ]; then
    shift; ./bin/csharp $@
elif [ "$1" = "version" ]; then
    dotnet package list -v q | grep -F '> Microformats ' | sed -Ee 's/ +/ /g' | cut -d ' ' -f 4
elif [ "$1" = "compile" ]; then
    dotnet build -v q -o bin --no-restore
elif [ "$1" = "setup" ]; then
    ver=`dotnet --version`
    sentinel="$HOME/.dotnet/$ver.dotnetFirstUseSentinel"
    if [ ! -f "$sentinel" ]; then
        mkdir -p `dirname "$sentinel"`
        touch "$sentinel"
    fi
    dotnet restore -v q
elif [ "$1" = "update" ]; then
    dotnet package update -v q
fi