#!/usr/bin/env bash

if [ "$1" = "test" ]; then
    ./bin/csharp "$2"
elif [ "$1" = "version" ]; then
    dotnet package list -v q | grep -F '> Microformats ' | sed 's/ \+/ /g' | cut -d ' ' -f 4
elif [ "$1" = "compile" ]; then
    dotnet build -v q -o bin
elif [ "$1" = "setup" ]; then
    dotnet restore -v q
elif [ "$1" = "update" ]; then
    dotnet package update -v q
fi