#!/usr/bin/env bash

if [ "$1" = "test" ]; then
    RUST_BACKTRACE=1 cargo run --locked -q test-one "$2"
elif [ "$1" = "version" ]; then
    cargo info -q microformats | grep '^version:' | awk '{print $2}'
elif [ "$1" = "compile" ]; then
    cargo build --locked -q
elif [ "$1" = "setup" ]; then
    cargo fetch --locked -q
elif [ "$1" = "update" ]; then
    cargo update -q
fi