#!/usr/bin/env bash

if [ "$1" = "test" ]; then
    HOME=`pwd` cargo run --locked -q test-one "$2"
elif [ "$1" = "version" ]; then
    HOME=`pwd` cargo info -q microformats | grep '^version:' | awk '{print $2}'
elif [ "$1" = "compile" ]; then
    HOME=`pwd` cargo build --locked -q
elif [ "$1" = "setup" ]; then
    HOME=`pwd` cargo fetch --locked -q
elif [ "$1" = "update" ]; then
    HOME=`pwd` cargo update -q
fi