#!/usr/bin/env bash

if [ "$1" = "test" ]; then
    shift; NODE_PATH=`pwd`"/node_modules" node "test-one.js" $@
elif [ "$1" = "version" ]; then
    npm ls -json | jq -r '.dependencies["microformat-node"].version | .'
elif [ "$1" = "compile" ]; then
    true
elif [ "$1" = "setup" ]; then
    npm install --silent
elif [ "$1" = "update" ]; then
    npm update --silent
fi