#!/usr/bin/env bash

if [ "$1" = "test" ]; then
    carton exec `pwd`/test-one.pl "$2"
elif [ "$1" = "version" ]; then
    carton show 'Web::Microformats2' | cut -d '-' -f 3
elif [ "$1" = "compile" ]; then
    true
elif [ "$1" = "setup" ]; then
    carton install >/dev/null
elif [ "$1" = "update" ]; then
    carton update >/dev/null
fi